---

oauth:
  access_token: ' '
  access_token_secret: ' '
  consumer_key: ' '
  consumer_secret: ' '

sqlite:
  dbpath: '/home/username/Saitan-bot/saitan.db'

interval: 3600

retweeted: 0

ignorelist:
  apps:
    - "twittbot.net"
  accounts:
  keywords:
    - "@"
    - "RT"
    - "QT"

wakeup: "こんにちは！さいたんbotがログインしたよ！"
shutdown: "ばいばーい！"

categories:
  - 'saitan'
  - 'tasty'
  - 'yuck'
  - 'chou'

replyonly:
  - 'mjkt'
  - 'saichan'
  - 'hentai'
  - 'love'
  - 'prpr'
  - 'momi'
  - 'oppai'

souiu:
  patterns:
    - 'ああ(.+?)ってそういう'
  prob: 0.2

fav:
  keywords:
    - 'ふぁぼ'
    - 'fav'

mjkt:
  keywords:
    - 'mjkt'
    - 'ｍｊｋｔ'
    - 'マジキチ'
  replies:
    - 'マジキチちがう'
    - 'ｍｊｋｔじゃないもん！'
    - 'ｍｊｋｔじゃねえよ'

hentai:
  keywords:
    - '変態'
    - 'ヘンタイ'
  replies:
    - '誰が変態だ'
    - 'ちがう'
    - '私は変態じゃない'
    - '変態じゃないし'
    - '私はぴゅあぴゅあよ★'

saitan:
  keywords:
    - 'さいたん'
  replies:
    - 'さいたんじゃないもん！'
    - 'さいたんじゃないってば！'
    - 'さいたんじゃないし！'
    - 'さいたんじゃねえ！'
    - 'さいたんじゃないもんっ'
    - 'さいたんちがう！'

love:
  keywords:
    - '(あい|愛)してる'
    - '(かわい|可愛)い'
  replies:
    - 'ありがとう(*´ω`*)'
    - 'えへへ///'
    - 'んもぅ〜'

saichan:
  keywords:
    - 'さいちゃん'
    - 'さいかく'
  replies:
    - 'なぁにー？'
    - 'よんだぁー？'
    - 'はぁーい！'

tasty:
  keywords:
    - 'ドクペ'
    - 'ドクターペッパー'
    - 'アイス'
  replies:
    - 'おいしいよね！'
    - 'だいすき！'
    - 'うまいっ！'
    - '買ってこい'

yuck:
  keywords:
    - 'スパム'
    - '貝'
    - 'コーヒー'
  replies:
    - 'うえぇええぇええぇ'
    - '苦手なの(´･ω･`)'
    - 'やめて＞＜'
    - 'にがいよぅ……＞＜'

prpr:
  keywords:
    - 'prpr'
    - 'ｐｒｐｒ'
    - 'ぺろぺろ'
    - 'ちゅっちゅ'
    - 'せっくす'
    - 'セックス'
  replies:
    - 'すんな！'
    - ' '
    - 'ぶっとばす'
    - 'しないでよぉ///'
    - 'やめてよぅ…'

momi:
  keywords:
    - '(も|揉)(む|ませろ)'
  replies:
    - 'ふざけんな'
    - '無いよ？'

oppai:
  keywords:
    - 'おっぱい'
  replies:
    - 'もふもふ'
    - '私におっぱいなど無かった'
    - '触れるもんなら触ってみな'

couple:
  keywords:
  replies:
    - '(*´ω`*)'
    - 'によによ'
    - 'にやにや'

chou:
  keywords:
    - '超'
  replies:
    - '超！！ｴｷｻｲﾀﾝ！！！！！'

...
